import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfólio | Pablo Alan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1
        className="inline-block text-lg text-white m-4 p-4 rounded bg-violet-500 
        hover:cursor-pointer"
      >
        Hello world
      </h1>
    </>
  )
}
