import Head from 'next/head'

import { About, Footer, Header, Skills, Work } from '@/containers'
import { Navbar } from '@/components'
import { styles } from '@/styles'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pablo Alan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <Navbar />
        <Header />
        <About />
        <Work />
        <Skills />
        <Footer />
      </div>
    </>
  )
}
